<?php
/**
* @file
* Bean plugin for showing tweets for a specified twitter user
*/

/**
* Implements hook_bean_types_api_info().
*/
function conductrics_1_bean_types_api_info() {
	return array('api' => 4);
}

/**
* Implements hook_init().
*/
function conductrics_1_init() {
	$path = drupal_get_path('module', 'conductrics_1') . '/assets';
	drupal_add_css($path.'/conductrics-experience.css', array('scope' => 'header') ); // include css before js (point is to avoid 'flicker')
	drupal_add_js($path .'/conductrics.jquery.js', array('scope' => 'header') ); // relies on jquery
	drupal_add_js($path .'/conductrics-experience.js', array('scope' => 'footer')); // relies on conductrics.jquery
	$conductrics_jquery_options = array(
		'conductrics-jquery' => array(
			'owner' => variable_get('conductrics_owner_code', ''),
			'apiKey' => variable_get('conductrics_api_key', ''),
			'baseUrl' => variable_get('conductrics_api_url', ''),
		)
	);
	drupal_add_js($conductrics_jquery_options, 'setting');
}

/**
* Implements hook_bean_types().
*/
function conductrics_1_bean_types() {
	$plugins = array();
	$plugins['conductrics_block'] = array(
		'label' => t('Conductrics Selection'), //note this appears as the Heading when creating a new block of this type
		'description' => t('Container for a Conductrics test or targeting/optimization.'),
		'handler' => array(
			'class' => 'ConductricsBlockBean',
			'parent' => 'bean',
			'path' => drupal_get_path('module', 'conductrics_1') . '/plugins/bean',
			'file' => 'conductrics_1.conductrics_block.inc',
		),
	);
	return $plugins;
}

/**
* Implements hook_menu().
*/
function conductrics_1_menu() {
  $items = array();

  $items['admin/config/content/conductrics_1'] = array(
    'title' => 'Conductrics',
    'description' => 'Provide your Conductrics account details here',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('conductrics_1_admin'),
    'access arguments' => array('administer conductrics_1 settings'),
    'type' => MENU_NORMAL_ITEM,
   );

  return $items;
}

/**
 * Implements hook_theme().
 */
function conductrics_1_theme() {
  $items = array();
  $items['agent_experience'] = array(
    'arguments' => array(
      'entities' => NULL,
      'view_mode'  => NULL,
      'agent_code' => NULL,
      'choice_code' => NULL,
    ),
    'file' => 'conductrics_1.theme.inc',
  );
  $items['agent_experience_child'] = array(
    'arguments' => array(
      'entity' => NULL,
      'view_mode'  => NULL,
    ),
    'file' => 'conductrics_1.theme.inc',
  );
  return $items;
}

function conductrics_1_admin() {
	$form = array();

	// TODO - store the values in one array, rather than seperate variables

	$form['conductrics_owner_code'] = array(
		'#type' => 'textfield',
		'#title' => t('Owner Code'),
		'#default_value' => variable_get('conductrics_owner_code', ''),
		'#size' => 30,
		'#maxlength' => 50,
		'#description' => t("Paste in from the Account > Keys page in Conductrics Console (starts with 'owner')"),
		'#required' => TRUE,
	);

	$form['conductrics_api_key'] = array(
		'#type' => 'textfield',
		'#title' => t('Runtime API Key'),
		'#default_value' => variable_get('conductrics_api_key', ''),
		'#size' => 30,
		'#maxlength' => 50,
		'#description' => t("Paste in from the Account > Keys page in Conductrics Console (starts with 'api')"),
		'#required' => TRUE,
	);

	$form['conductrics_admin_key'] = array(
		'#type' => 'textfield',
		'#title' => t('Admin API Key'),
		'#default_value' => variable_get('conductrics_admin_key', ''),
		'#size' => 30,
		'#maxlength' => 50,
		'#description' => t("Paste in from the Account > Keys page in Conductrics Console (starts with 'admin')"),
		'#required' => TRUE,
	);

	$form['conductrics_api_url'] = array(
		'#type' => 'textfield',
		'#title' => t('API Server URL'),
		'#default_value' => variable_get('conductrics_api_url', 'https://api.conductrics.com'),
		'#size' => 30,
		'#maxlength' => 50,
		'#description' => t("Adjust this URL only if using a custom server from Conductrics."),
		'#required' => FALSE,
	);

	$form['conductrics_console_url'] = array(
		'#type' => 'textfield',
		'#title' => t('Console URL'),
		'#default_value' => variable_get('conductrics_console_url', 'https://console.conductrics.com'),
		'#size' => 30,
		'#maxlength' => 50,
		'#description' => t("Adjust this URL only if using a custom server from Conductrics."),
		'#required' => FALSE,
	);

	return system_settings_form($form);
}

/**
* Implements hook_elements().
*/
function conductrics_1_element_info() {
  return array(
    'node_selection' => array(
      '#input' => TRUE,
      '#tree' => TRUE,
      '#process' => array('conductrics_1_element_process_callback'),
    ),
  );
}


/**
* Generates form elements for my element.
*/
function conductrics_1_element_process_callback($element, &$form_state) {

  // Add two textfields to the element
  $element['criteria'] = array(
    '#type' => 'textfield',
    '#title' => t('Textfield 1'),
    '#size' => 10,
    '#ajax' => array(
    	'callback' => 'conductrics_1_element_callback',
    	'wrapper' => 'conductrics_1_dynamic_div',
    	'method' => 'replace',
    	'effect' => 'fade',
    ),
  );

  /*
  $element['checkboxes_fieldset'] = array(
    '#title' => t("Generated Stuff"),
    '#prefix' => '<div id="conductrics_1_dynamic_div">',
    '#suffix' => '</div>',
    '#type' => 'fieldset',
    '#description' => t('This is where we get automatically generated checkboxes'),
  );*/

	$options = array();
  	if (isset($form_state['values']['settings']['nodes']['criteria'])) {
	  	$criteria = $form_state['values']['settings']['nodes']['criteria'];
	  	$all_beans = bean_get_all_beans();
	  	foreach ($all_beans as $node) {
	  		if (stristr($node->label(), $criteria)) {
				$nid = $node->internalIdentifier();
	  			$options[$nid] = array(
	  				'id' => $node->internalIdentifier(),
					'title' => $node->label(),
	  			);
	  		}
	  	}
  	};

	$element['items'] = array(
		'#type' => 'tableselect',
		'#multiple' => FALSE,
		'#header' => array(
			'title' => array(
				'data' => t("Title"),
				'width' => '100%',
			),
			'id' => t("Id"),
	),
	'#options' => $options,
	'#title' => 'Blocks',
    '#prefix' => '<div id="conductrics_1_dynamic_div">',
    '#suffix' => '</div>',
	);

  return $element;
}

function conductrics_1_element_callback($form, $form_state) {
  	return $form['settings']['nodes']['items'];
}
